### ISSUE TITLE
play with filebeat configuration

### ISSUE THREAD

**Issue by nfilipov** [nfilipov/NotesAlize#18]
related to #8 
we want to run a simple filebeat configuration:
- standalone 
- sends to output (elastic, logstash, whatever) some basic stuff for now
We'll figure out the threading and the architecture of the pipeline and indexing next.

**Comment by nfilipov** [comment]
paths have to be glob-based, so we'll play with a local file for now.

**Comment by nfilipov** [comment]
basic start is here:
```yml
#=========================== Filebeat inputs =============================
filebeat.inputs:
- type: log
  # paths that should be crawled and fetched. Glob based paths
  paths:
    -  /home/it/nf/filebeat_test.log
    tags: ["test"]

filebeat.config:
  reload.enabled: true
  ignore_older: 1h
  close_removed: true
  scan_frequency: 5s
```

the meaning of the filebeat.config options we selected: can be found in filebeat doc.
