### ISSUE TITLE
Start elasticsearch

### ISSUE THREAD

**Issue by nfilipov** [nfilipov/NotesAlize#20]
start elasticsearch, push its configuration on svn.
do not worry about indices for now
We should want elastic search just as a way to have kibana up and running (if elasticsearch is not up, kibana won't start).

**Comment by nfilipov** [comment]
elastic started with basic test configuration

```yaml
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: alize-uat-elastic
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: alize-uat-elastic-master
node.master: true
node.data: true
node.ingest: true
node.ml: true
# data and ingest options should be set with care
# ultimately we would like several nodes to separate master from data and ingest nodes
# ml node is a test for now
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /media/sda1/nf/data/elasticsearch
#
# Path to log files:
#
path.logs: /media/sda1/nf/logs/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 172.18.49.53
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.seed_hosts: ["[::1]", "127.0.0.1","172.18.49.53"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
cluster.initial_master_nodes: alize-uat-elastic-master
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
#action.auto_create_index: .*
```
